### ISSUE TITLE
How can I run API using given datasets? It would be fine if you can explain an example.

### ISSUE THREAD

**Issue by Amila-Rukshan** [minhptx/iswc-2016-semantic-labeling#1]

**Comment by Amila-Rukshan** [comment]
**command**
$ sudo docker -compose up

**error log**
Starting semantic-labeling-es ...
Starting semantic-labeling-es ... done
Attaching to semantic-labeling-es
semantic-labeling-es | [2019-01-19T10:29:55,980][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
semantic-labeling-es | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'path.scripts' (/usr/share/elasticsearch/config/scripts)
semantic-labeling-es |  at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es | Caused by: java.lang.IllegalStateException: Unable to access 'path.scripts' (/usr/share/elasticsearch/config/scripts)
semantic-labeling-es |  at org.elasticsearch.bootstrap.Security.addPath(Security.java:450) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:282) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:246) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Security.configure(Security.java:119) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:228) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  ... 6 more
semantic-labeling-es | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/scripts
semantic-labeling-es |  at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:1.8.0_181]
semantic-labeling-es |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_181]
semantic-labeling-es |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_181]
semantic-labeling-es |  at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:1.8.0_181]
semantic-labeling-es |  at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_181]
semantic-labeling-es |  at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_181]
semantic-labeling-es |  at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_181]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:492) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Security.addPath(Security.java:448) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:282) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:246) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Security.configure(Security.java:119) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:228) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.14.jar:5.6.14]
semantic-labeling-es |  ... 6 more
semantic-labeling-es exited with code 1

**command**
 sudo bin/semantic_labeling.sh /museum /soccer /weather

**This is the error log**

usage: Semantic labeling API [-h] --train_dataset TRAIN_DATASET --test_dataset
                             TEST_DATASET [--train_dataset2 TRAIN_DATASET2]
                             [--evaluate_train_set EVALUATE_TRAIN_SET]
                             [--reuse_rf_model REUSE_RF_MODEL]
Semantic labeling API: error: argument --train_dataset is required
